// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querier

import (
	"context"
	"encoding/json"
)

type Querier interface {
	GetCounter(ctx context.Context) (*Counter, error)
	GetSymphonyState(ctx context.Context, workflowID string) (*GetSymphonyStateRow, error)
	IncrementCounter(ctx context.Context) error
	InsertSymphonyCompletedAttempt(ctx context.Context, arg InsertSymphonyCompletedAttemptParams) error
	ListSymphonyCompletedAttempts(ctx context.Context, arg ListSymphonyCompletedAttemptsParams) ([]json.RawMessage, error)
	PruneSymphonyCompletedAttempts(ctx context.Context, arg PruneSymphonyCompletedAttemptsParams) error
	UpsertSymphonyState(ctx context.Context, arg UpsertSymphonyStateParams) error
}

var _ Querier = (*Queries)(nil)
