// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: symphony_state.sql

package querier

import (
	"context"
	"encoding/json"
	"time"
)

type SymphonyState struct {
	ID                int32
	CodexInputTokens  int64
	CodexOutputTokens int64
	CodexTotalTokens  int64
	RateLimits        json.RawMessage
	UpdatedAt         time.Time
}

type UpsertSymphonyStateParams struct {
	CodexInputTokens  int64
	CodexOutputTokens int64
	CodexTotalTokens  int64
	RateLimits        json.RawMessage
}

type ListSymphonyCompletedAttemptsRow struct {
	Entry json.RawMessage
}

const getSymphonyState = `-- name: GetSymphonyState :one
SELECT
    id,
    codex_input_tokens,
    codex_output_tokens,
    codex_total_tokens,
    rate_limits,
    updated_at
FROM symphony_state
WHERE id = 1
`

func (q *Queries) GetSymphonyState(ctx context.Context) (*SymphonyState, error) {
	row := q.db.QueryRow(ctx, getSymphonyState)
	var i SymphonyState
	err := row.Scan(
		&i.ID,
		&i.CodexInputTokens,
		&i.CodexOutputTokens,
		&i.CodexTotalTokens,
		&i.RateLimits,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertSymphonyState = `-- name: UpsertSymphonyState :exec
INSERT INTO symphony_state (
    id,
    codex_input_tokens,
    codex_output_tokens,
    codex_total_tokens,
    rate_limits,
    updated_at
)
VALUES (1, $1, $2, $3, $4, now())
ON CONFLICT (id) DO UPDATE SET
    codex_input_tokens = EXCLUDED.codex_input_tokens,
    codex_output_tokens = EXCLUDED.codex_output_tokens,
    codex_total_tokens = EXCLUDED.codex_total_tokens,
    rate_limits = EXCLUDED.rate_limits,
    updated_at = now()
`

func (q *Queries) UpsertSymphonyState(ctx context.Context, arg UpsertSymphonyStateParams) error {
	_, err := q.db.Exec(ctx, upsertSymphonyState, arg.CodexInputTokens, arg.CodexOutputTokens, arg.CodexTotalTokens, arg.RateLimits)
	return err
}

const insertSymphonyCompletedAttempt = `-- name: InsertSymphonyCompletedAttempt :exec
INSERT INTO symphony_completed_attempts (entry)
VALUES ($1)
`

func (q *Queries) InsertSymphonyCompletedAttempt(ctx context.Context, entry json.RawMessage) error {
	_, err := q.db.Exec(ctx, insertSymphonyCompletedAttempt, entry)
	return err
}

const pruneSymphonyCompletedAttempts = `-- name: PruneSymphonyCompletedAttempts :exec
DELETE FROM symphony_completed_attempts
WHERE id < (
    SELECT id
    FROM symphony_completed_attempts
    ORDER BY id DESC
    OFFSET GREATEST($1 - 1, 0)
    LIMIT 1
)
`

func (q *Queries) PruneSymphonyCompletedAttempts(ctx context.Context, keep int32) error {
	_, err := q.db.Exec(ctx, pruneSymphonyCompletedAttempts, keep)
	return err
}

const listSymphonyCompletedAttempts = `-- name: ListSymphonyCompletedAttempts :many
SELECT entry
FROM symphony_completed_attempts
ORDER BY id DESC
LIMIT $1
`

func (q *Queries) ListSymphonyCompletedAttempts(ctx context.Context, limit int32) ([]ListSymphonyCompletedAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listSymphonyCompletedAttempts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSymphonyCompletedAttemptsRow
	for rows.Next() {
		var i ListSymphonyCompletedAttemptsRow
		if err := rows.Scan(&i.Entry); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
