// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package apigen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/gofiber/fiber/v2"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// CodexTotals defines model for CodexTotals.
type CodexTotals struct {
	InputTokens    int32   `json:"input_tokens"`
	OutputTokens   int32   `json:"output_tokens"`
	SecondsRunning float64 `json:"seconds_running"`
	TotalTokens    int32   `json:"total_tokens"`
}

// Counter defines model for Counter.
type Counter struct {
	Count int32 `json:"count"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status               string  `json:"status"`
	SymphonyLastError    *string `json:"symphony_last_error"`
	SymphonyRunning      bool    `json:"symphony_running"`
	SymphonyWorkflowPath *string `json:"symphony_workflow_path"`
}

// StartSymphonyRequest defines model for StartSymphonyRequest.
type StartSymphonyRequest struct {
	// HttpPort Optional Symphony debug HTTP port override. Set to -1 to disable even if WORKFLOW.md sets server.port.
	HttpPort *int32 `json:"http_port"`

	// WorkflowPath Optional path to WORKFLOW.md. If omitted, server default is used.
	WorkflowPath *string `json:"workflow_path,omitempty"`
}

// StartSymphonyResult defines model for StartSymphonyResult.
type StartSymphonyResult struct {
	Running      bool    `json:"running"`
	WorkflowPath *string `json:"workflow_path"`
}

// StopSymphonyResult defines model for StopSymphonyResult.
type StopSymphonyResult struct {
	Running bool `json:"running"`
}

// SymphonyBlockerRef defines model for SymphonyBlockerRef.
type SymphonyBlockerRef struct {
	Id         *string `json:"id"`
	Identifier *string `json:"identifier"`
	State      *string `json:"state"`
}

// SymphonyIssue defines model for SymphonyIssue.
type SymphonyIssue struct {
	BlockedBy   *[]SymphonyBlockerRef `json:"blocked_by,omitempty"`
	BranchName  *string               `json:"branch_name"`
	CreatedAt   *time.Time            `json:"created_at"`
	Description *string               `json:"description"`
	Id          string                `json:"id"`
	Identifier  string                `json:"identifier"`
	Labels      *[]string             `json:"labels,omitempty"`
	Priority    *int32                `json:"priority"`
	State       string                `json:"state"`
	Title       string                `json:"title"`
	UpdatedAt   *time.Time            `json:"updated_at"`
	Url         *string               `json:"url"`
}

// SymphonyLiveSession defines model for SymphonyLiveSession.
type SymphonyLiveSession struct {
	CodexAppServerPid  *int32     `json:"codex_app_server_pid"`
	CodexInputTokens   int32      `json:"codex_input_tokens"`
	CodexOutputTokens  int32      `json:"codex_output_tokens"`
	CodexTotalTokens   int32      `json:"codex_total_tokens"`
	LastCodexEvent     *string    `json:"last_codex_event"`
	LastCodexMessage   *string    `json:"last_codex_message"`
	LastCodexTimestamp *time.Time `json:"last_codex_timestamp"`
	SessionId          *string    `json:"session_id"`
	ThreadId           *string    `json:"thread_id"`
	TurnCount          int32      `json:"turn_count"`
	TurnId             *string    `json:"turn_id"`
}

// SymphonyRetryEntry defines model for SymphonyRetryEntry.
type SymphonyRetryEntry struct {
	Attempt    int32     `json:"attempt"`
	DelayType  *string   `json:"delay_type"`
	DueAt      time.Time `json:"due_at"`
	Error      *string   `json:"error"`
	Identifier string    `json:"identifier"`
	IssueId    string    `json:"issue_id"`
}

// SymphonyRunningEntry defines model for SymphonyRunningEntry.
type SymphonyRunningEntry struct {
	Attempt         *int32              `json:"attempt"`
	Issue           SymphonyIssue       `json:"issue"`
	IssueId         string              `json:"issue_id"`
	IssueIdentifier string              `json:"issue_identifier"`
	Live            SymphonyLiveSession `json:"live"`
	Phase           string              `json:"phase"`
	StartedAt       time.Time           `json:"started_at"`
	WorkspacePath   string              `json:"workspace_path"`
}

// SymphonySnapshot defines model for SymphonySnapshot.
type SymphonySnapshot struct {
	CodexTotals CodexTotals             `json:"codex_totals"`
	RateLimits  *map[string]interface{} `json:"rate_limits,omitempty"`
	Retrying    []SymphonyRetryEntry    `json:"retrying"`
	Running     []SymphonyRunningEntry  `json:"running"`
}

// StartSymphonyJSONRequestBody defines body for StartSymphony for application/json ContentType.
type StartSymphonyJSONRequestBody = StartSymphonyRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCounter request
	GetCounter(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// IncrementCounter request
	IncrementCounter(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSymphonySnapshot request
	GetSymphonySnapshot(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartSymphonyWithBody request with any body
	StartSymphonyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	StartSymphony(ctx context.Context, body StartSymphonyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StopSymphony request
	StopSymphony(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCounter(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCounterRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) IncrementCounter(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewIncrementCounterRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSymphonySnapshot(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSymphonySnapshotRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartSymphonyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartSymphonyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartSymphony(ctx context.Context, body StartSymphonyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartSymphonyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StopSymphony(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStopSymphonyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCounterRequest generates requests for GetCounter
func NewGetCounterRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/counter")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewIncrementCounterRequest generates requests for IncrementCounter
func NewIncrementCounterRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/counter")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSymphonySnapshotRequest generates requests for GetSymphonySnapshot
func NewGetSymphonySnapshotRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/symphony/snapshot")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStartSymphonyRequest calls the generic StartSymphony builder with application/json body
func NewStartSymphonyRequest(server string, body StartSymphonyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewStartSymphonyRequestWithBody(server, "application/json", bodyReader)
}

// NewStartSymphonyRequestWithBody generates requests for StartSymphony with any type of body
func NewStartSymphonyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/symphony/start")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewStopSymphonyRequest generates requests for StopSymphony
func NewStopSymphonyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/symphony/stop")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCounterWithResponse request
	GetCounterWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCounterResponse, error)

	// IncrementCounterWithResponse request
	IncrementCounterWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*IncrementCounterResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// GetSymphonySnapshotWithResponse request
	GetSymphonySnapshotWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSymphonySnapshotResponse, error)

	// StartSymphonyWithBodyWithResponse request with any body
	StartSymphonyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartSymphonyResponse, error)

	StartSymphonyWithResponse(ctx context.Context, body StartSymphonyJSONRequestBody, reqEditors ...RequestEditorFn) (*StartSymphonyResponse, error)

	// StopSymphonyWithResponse request
	StopSymphonyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*StopSymphonyResponse, error)
}

type GetCounterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Counter
}

// Status returns HTTPResponse.Status
func (r GetCounterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCounterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type IncrementCounterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r IncrementCounterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r IncrementCounterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSymphonySnapshotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SymphonySnapshot
}

// Status returns HTTPResponse.Status
func (r GetSymphonySnapshotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSymphonySnapshotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StartSymphonyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *StartSymphonyResult
}

// Status returns HTTPResponse.Status
func (r StartSymphonyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartSymphonyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StopSymphonyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *StopSymphonyResult
}

// Status returns HTTPResponse.Status
func (r StopSymphonyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StopSymphonyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCounterWithResponse request returning *GetCounterResponse
func (c *ClientWithResponses) GetCounterWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCounterResponse, error) {
	rsp, err := c.GetCounter(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCounterResponse(rsp)
}

// IncrementCounterWithResponse request returning *IncrementCounterResponse
func (c *ClientWithResponses) IncrementCounterWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*IncrementCounterResponse, error) {
	rsp, err := c.IncrementCounter(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseIncrementCounterResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// GetSymphonySnapshotWithResponse request returning *GetSymphonySnapshotResponse
func (c *ClientWithResponses) GetSymphonySnapshotWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSymphonySnapshotResponse, error) {
	rsp, err := c.GetSymphonySnapshot(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSymphonySnapshotResponse(rsp)
}

// StartSymphonyWithBodyWithResponse request with arbitrary body returning *StartSymphonyResponse
func (c *ClientWithResponses) StartSymphonyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartSymphonyResponse, error) {
	rsp, err := c.StartSymphonyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartSymphonyResponse(rsp)
}

func (c *ClientWithResponses) StartSymphonyWithResponse(ctx context.Context, body StartSymphonyJSONRequestBody, reqEditors ...RequestEditorFn) (*StartSymphonyResponse, error) {
	rsp, err := c.StartSymphony(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartSymphonyResponse(rsp)
}

// StopSymphonyWithResponse request returning *StopSymphonyResponse
func (c *ClientWithResponses) StopSymphonyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*StopSymphonyResponse, error) {
	rsp, err := c.StopSymphony(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStopSymphonyResponse(rsp)
}

// ParseGetCounterResponse parses an HTTP response from a GetCounterWithResponse call
func ParseGetCounterResponse(rsp *http.Response) (*GetCounterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCounterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Counter
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseIncrementCounterResponse parses an HTTP response from a IncrementCounterWithResponse call
func ParseIncrementCounterResponse(rsp *http.Response) (*IncrementCounterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &IncrementCounterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSymphonySnapshotResponse parses an HTTP response from a GetSymphonySnapshotWithResponse call
func ParseGetSymphonySnapshotResponse(rsp *http.Response) (*GetSymphonySnapshotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSymphonySnapshotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SymphonySnapshot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseStartSymphonyResponse parses an HTTP response from a StartSymphonyWithResponse call
func ParseStartSymphonyResponse(rsp *http.Response) (*StartSymphonyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartSymphonyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StartSymphonyResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseStopSymphonyResponse parses an HTTP response from a StopSymphonyWithResponse call
func ParseStopSymphonyResponse(rsp *http.Response) (*StopSymphonyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StopSymphonyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StopSymphonyResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Counter
	// (GET /counter)
	GetCounter(c *fiber.Ctx) error
	// Increment Counter
	// (POST /counter)
	IncrementCounter(c *fiber.Ctx) error
	// Health Check
	// (GET /health)
	GetHealth(c *fiber.Ctx) error
	// Symphony Snapshot
	// (GET /symphony/snapshot)
	GetSymphonySnapshot(c *fiber.Ctx) error
	// Start Symphony
	// (POST /symphony/start)
	StartSymphony(c *fiber.Ctx) error
	// Stop Symphony
	// (POST /symphony/stop)
	StopSymphony(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetCounter operation middleware
func (siw *ServerInterfaceWrapper) GetCounter(c *fiber.Ctx) error {

	return siw.Handler.GetCounter(c)
}

// IncrementCounter operation middleware
func (siw *ServerInterfaceWrapper) IncrementCounter(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{"x.OperationPermit(c, operationID)"})

	return siw.Handler.IncrementCounter(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *fiber.Ctx) error {

	return siw.Handler.GetHealth(c)
}

// GetSymphonySnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetSymphonySnapshot(c *fiber.Ctx) error {

	return siw.Handler.GetSymphonySnapshot(c)
}

// StartSymphony operation middleware
func (siw *ServerInterfaceWrapper) StartSymphony(c *fiber.Ctx) error {

	return siw.Handler.StartSymphony(c)
}

// StopSymphony operation middleware
func (siw *ServerInterfaceWrapper) StopSymphony(c *fiber.Ctx) error {

	return siw.Handler.StopSymphony(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/counter", wrapper.GetCounter)

	router.Post(options.BaseURL+"/counter", wrapper.IncrementCounter)

	router.Get(options.BaseURL+"/health", wrapper.GetHealth)

	router.Get(options.BaseURL+"/symphony/snapshot", wrapper.GetSymphonySnapshot)

	router.Post(options.BaseURL+"/symphony/start", wrapper.StartSymphony)

	router.Post(options.BaseURL+"/symphony/stop", wrapper.StopSymphony)

}
