// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getCounter, getHealth, getSymphonySnapshot, getSymphonyWorkflows, incrementCounter, type Options, startSymphony, stopSymphony } from '../sdk.gen';
import type { GetCounterData, GetCounterResponse, GetHealthData, GetHealthResponse, GetSymphonySnapshotData, GetSymphonySnapshotResponse, GetSymphonyWorkflowsData, GetSymphonyWorkflowsResponse, IncrementCounterData, StartSymphonyData, StartSymphonyResponse, StopSymphonyData, StopSymphonyResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

/**
 * Health Check
 *
 * Liveness/readiness endpoint for the API server.
 */
export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<GetHealthResponse, DefaultError, GetHealthResponse, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

export const getSymphonySnapshotQueryKey = (options?: Options<GetSymphonySnapshotData>) => createQueryKey('getSymphonySnapshot', options);

/**
 * Symphony Snapshot
 *
 * Get a snapshot of Symphony orchestrator state for the web UI.
 */
export const getSymphonySnapshotOptions = (options?: Options<GetSymphonySnapshotData>) => queryOptions<GetSymphonySnapshotResponse, DefaultError, GetSymphonySnapshotResponse, ReturnType<typeof getSymphonySnapshotQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSymphonySnapshot({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSymphonySnapshotQueryKey(options)
});

/**
 * Start Symphony
 *
 * Start the Symphony orchestrator (idempotent).
 */
export const startSymphonyMutation = (options?: Partial<Options<StartSymphonyData>>): UseMutationOptions<StartSymphonyResponse, DefaultError, Options<StartSymphonyData>> => {
    const mutationOptions: UseMutationOptions<StartSymphonyResponse, DefaultError, Options<StartSymphonyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await startSymphony({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Stop Symphony
 *
 * Stop the Symphony orchestrator (idempotent).
 */
export const stopSymphonyMutation = (options?: Partial<Options<StopSymphonyData>>): UseMutationOptions<StopSymphonyResponse, DefaultError, Options<StopSymphonyData>> => {
    const mutationOptions: UseMutationOptions<StopSymphonyResponse, DefaultError, Options<StopSymphonyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await stopSymphony({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSymphonyWorkflowsQueryKey = (options?: Options<GetSymphonyWorkflowsData>) => createQueryKey('getSymphonyWorkflows', options);

/**
 * Symphony Workflows
 *
 * List known Symphony workflows for the web UI.
 */
export const getSymphonyWorkflowsOptions = (options?: Options<GetSymphonyWorkflowsData>) => queryOptions<GetSymphonyWorkflowsResponse, DefaultError, GetSymphonyWorkflowsResponse, ReturnType<typeof getSymphonyWorkflowsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSymphonyWorkflows({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSymphonyWorkflowsQueryKey(options)
});

export const getCounterQueryKey = (options?: Options<GetCounterData>) => createQueryKey('getCounter', options);

/**
 * Get Counter
 *
 * Retrieve the current counter value
 */
export const getCounterOptions = (options?: Options<GetCounterData>) => queryOptions<GetCounterResponse, DefaultError, GetCounterResponse, ReturnType<typeof getCounterQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCounter({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCounterQueryKey(options)
});

/**
 * Increment Counter
 *
 * Increment the counter by a specified amount
 */
export const incrementCounterMutation = (options?: Partial<Options<IncrementCounterData>>): UseMutationOptions<unknown, DefaultError, Options<IncrementCounterData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<IncrementCounterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await incrementCounter({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
