// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  GetCounterData,
  GetCounterResponses,
  GetHealthData,
  GetHealthResponses,
  GetSymphonySnapshotData,
  GetSymphonySnapshotResponses,
  IncrementCounterData,
  IncrementCounterResponses,
  StartSymphonyData,
  StartSymphonyResponses,
  StopSymphonyData,
  StopSymphonyResponses,
} from "./types.gen";
import {
  zGetCounterData,
  zGetHealthData,
  zGetSymphonySnapshotData,
  zIncrementCounterData,
  zStartSymphonyData,
  zStopSymphonyData,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * Liveness/readiness endpoint for the API server.
 */
export const getHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetHealthData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetHealthData.parseAsync(data),
    url: "/health",
    ...options,
  });

/**
 * Symphony Snapshot
 *
 * Get a snapshot of Symphony orchestrator state for the web UI.
 */
export const getSymphonySnapshot = <ThrowOnError extends boolean = false>(
  options?: Options<GetSymphonySnapshotData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetSymphonySnapshotResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetSymphonySnapshotData.parseAsync(data),
    url: "/symphony/snapshot",
    ...options,
  });

/**
 * Start Symphony
 *
 * Start the Symphony orchestrator (idempotent).
 */
export const startSymphony = <ThrowOnError extends boolean = false>(
  options?: Options<StartSymphonyData, ThrowOnError>,
) =>
  (options?.client ?? client).post<StartSymphonyResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zStartSymphonyData.parseAsync(data),
    url: "/symphony/start",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Stop Symphony
 *
 * Stop the Symphony orchestrator (idempotent).
 */
export const stopSymphony = <ThrowOnError extends boolean = false>(
  options?: Options<StopSymphonyData, ThrowOnError>,
) =>
  (options?.client ?? client).post<StopSymphonyResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zStopSymphonyData.parseAsync(data),
    url: "/symphony/stop",
    ...options,
  });

/**
 * Get Counter
 *
 * Retrieve the current counter value
 */
export const getCounter = <ThrowOnError extends boolean = false>(
  options?: Options<GetCounterData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetCounterResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetCounterData.parseAsync(data),
    url: "/counter",
    ...options,
  });

/**
 * Increment Counter
 *
 * Increment the counter by a specified amount
 */
export const incrementCounter = <ThrowOnError extends boolean = false>(
  options?: Options<IncrementCounterData, ThrowOnError>,
) =>
  (options?.client ?? client).post<IncrementCounterResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zIncrementCounterData.parseAsync(data),
    url: "/counter",
    ...options,
  });
