// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type HealthResponse = {
    status: string;
    symphony_running: boolean;
    symphony_workflow_path?: string | null;
    symphony_last_error?: string | null;
    /**
     * The port of Symphony's debug HTTP server, if running.
     */
    symphony_http_port?: number | null;
};

export type StartSymphonyRequest = {
    /**
     * Optional path to WORKFLOW.md. If omitted, server default is used.
     */
    workflow_path?: string;
    /**
     * Optional Symphony debug HTTP port override. Set to -1 to disable even if WORKFLOW.md sets server.port.
     */
    http_port?: number | null;
};

export type StartSymphonyResult = {
    running: boolean;
    workflow_path?: string | null;
};

export type StopSymphonyResult = {
    running: boolean;
};

export type SymphonySnapshot = {
    running: Array<SymphonyRunningEntry>;
    retrying: Array<SymphonyRetryEntry>;
    completed?: Array<SymphonyCompletedEntry>;
    codex_totals: CodexTotals;
    rate_limits?: {
        [key: string]: unknown;
    };
};

export type SymphonyRunningEntry = {
    issue: SymphonyIssue;
    issue_id: string;
    issue_identifier: string;
    attempt?: number | null;
    workspace_path: string;
    started_at: string;
    phase: string;
    live: SymphonyLiveSession;
};

export type LiveEvent = {
    ts: string;
    event: string;
    message?: string | null;
};

export type SymphonyLiveSession = {
    session_id?: string | null;
    thread_id?: string | null;
    turn_id?: string | null;
    codex_app_server_pid?: number | null;
    last_codex_event?: string | null;
    last_codex_timestamp?: string | null;
    last_codex_message?: string | null;
    codex_input_tokens: number;
    codex_output_tokens: number;
    codex_total_tokens: number;
    turn_count: number;
    event_log?: Array<LiveEvent>;
};

export type SymphonyRetryEntry = {
    issue_id: string;
    identifier: string;
    attempt: number;
    due_at: string;
    error?: string | null;
    delay_type?: string | null;
};

export type SymphonyCompletedEntry = {
    issue: SymphonyIssue;
    issue_id: string;
    issue_identifier: string;
    attempt?: number | null;
    workspace_path?: string | null;
    started_at: string;
    ended_at: string;
    duration_secs: number;
    status: string;
    error?: string | null;
    codex_input_tokens: number;
    codex_output_tokens: number;
    codex_total_tokens: number;
    turns_run: number;
    thread_id?: string | null;
    turn_id?: string | null;
    last_codex_event?: string | null;
    last_codex_message?: string | null;
};

export type SymphonyIssue = {
    id: string;
    identifier: string;
    title: string;
    description?: string | null;
    priority?: number | null;
    state: string;
    branch_name?: string | null;
    url?: string | null;
    labels?: Array<string>;
    blocked_by?: Array<SymphonyBlockerRef>;
    created_at?: string | null;
    updated_at?: string | null;
};

export type SymphonyBlockerRef = {
    id?: string | null;
    identifier?: string | null;
    state?: string | null;
};

export type CodexTotals = {
    input_tokens: number;
    output_tokens: number;
    total_tokens: number;
    seconds_running: number;
};

export type Counter = {
    count: number;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Health status
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetSymphonySnapshotData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/symphony/snapshot';
};

export type GetSymphonySnapshotResponses = {
    /**
     * Current Symphony snapshot
     */
    200: SymphonySnapshot;
};

export type GetSymphonySnapshotResponse = GetSymphonySnapshotResponses[keyof GetSymphonySnapshotResponses];

export type StartSymphonyData = {
    body?: StartSymphonyRequest;
    path?: never;
    query?: never;
    url: '/symphony/start';
};

export type StartSymphonyResponses = {
    /**
     * Start result
     */
    200: StartSymphonyResult;
};

export type StartSymphonyResponse = StartSymphonyResponses[keyof StartSymphonyResponses];

export type StopSymphonyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/symphony/stop';
};

export type StopSymphonyResponses = {
    /**
     * Stop result
     */
    200: StopSymphonyResult;
};

export type StopSymphonyResponse = StopSymphonyResponses[keyof StopSymphonyResponses];

export type GetCounterData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/counter';
};

export type GetCounterResponses = {
    /**
     * The current counter value
     */
    200: Counter;
};

export type GetCounterResponse = GetCounterResponses[keyof GetCounterResponses];

export type IncrementCounterData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/counter';
};

export type IncrementCounterResponses = {
    /**
     * The increment was accepted
     */
    202: unknown;
};
