// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zStartSymphonyRequest = z.object({
    workflow_id: z.string().optional(),
    workflow_path: z.string().optional(),
    http_port: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish()
});

export const zStartSymphonyResult = z.object({
    running: z.boolean(),
    workflow_id: z.string().nullish(),
    workflow_path: z.string().nullish()
});

export const zStopSymphonyResult = z.object({
    running: z.boolean(),
    workflow_id: z.string().nullish()
});

export const zSymphonyWorkflow = z.object({
    id: z.string(),
    workflow_path: z.string(),
    running: z.boolean(),
    last_error: z.string().nullish(),
    http_port: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish()
});

export const zHealthResponse = z.object({
    status: z.string(),
    symphony_running: z.boolean(),
    symphony_active_workflow_id: z.string().nullish(),
    symphony_workflow_path: z.string().nullish(),
    symphony_last_error: z.string().nullish(),
    symphony_http_port: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    symphony_workflows: z.array(zSymphonyWorkflow).nullish()
});

export const zSymphonyWorkflowsResponse = z.object({
    workflows: z.array(zSymphonyWorkflow),
    active_workflow_id: z.string().nullish()
});

export const zLiveEvent = z.object({
    ts: z.iso.datetime(),
    event: z.string(),
    message: z.string().nullish()
});

export const zSymphonyLiveSession = z.object({
    session_id: z.string().nullish(),
    thread_id: z.string().nullish(),
    turn_id: z.string().nullish(),
    agent_pid: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    last_agent_event: z.string().nullish(),
    last_agent_timestamp: z.iso.datetime().nullish(),
    last_agent_message: z.string().nullish(),
    input_tokens: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    output_tokens: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    total_tokens: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    turn_count: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    event_log: z.array(zLiveEvent).optional()
});

export const zSymphonyRetryEntry = z.object({
    issue_id: z.string(),
    identifier: z.string(),
    attempt: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    due_at: z.iso.datetime(),
    error: z.string().nullish(),
    delay_type: z.string().nullish()
});

export const zSymphonyBlockerRef = z.object({
    id: z.string().nullish(),
    identifier: z.string().nullish(),
    state: z.string().nullish()
});

export const zSymphonyIssue = z.object({
    id: z.string(),
    identifier: z.string(),
    title: z.string(),
    description: z.string().nullish(),
    priority: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    state: z.string(),
    branch_name: z.string().nullish(),
    url: z.string().nullish(),
    labels: z.array(z.string()).optional(),
    blocked_by: z.array(zSymphonyBlockerRef).optional(),
    created_at: z.iso.datetime().nullish(),
    updated_at: z.iso.datetime().nullish()
});

export const zSymphonyRunningEntry = z.object({
    issue: zSymphonyIssue,
    issue_id: z.string(),
    issue_identifier: z.string(),
    attempt: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    workspace_path: z.string(),
    started_at: z.iso.datetime(),
    phase: z.string(),
    live: zSymphonyLiveSession
});

export const zSymphonyCompletedEntry = z.object({
    issue: zSymphonyIssue,
    issue_id: z.string(),
    issue_identifier: z.string(),
    attempt: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    workspace_path: z.string().nullish(),
    started_at: z.iso.datetime(),
    ended_at: z.iso.datetime(),
    duration_secs: z.number(),
    status: z.string(),
    error: z.string().nullish(),
    input_tokens: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    output_tokens: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    total_tokens: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    turns_run: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    thread_id: z.string().nullish(),
    turn_id: z.string().nullish(),
    last_agent_event: z.string().nullish(),
    last_agent_message: z.string().nullish()
});

export const zAgentTotals = z.object({
    input_tokens: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    output_tokens: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    total_tokens: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    seconds_running: z.number()
});

export const zSymphonySnapshot = z.object({
    running: z.array(zSymphonyRunningEntry),
    retrying: z.array(zSymphonyRetryEntry),
    completed: z.array(zSymphonyCompletedEntry).optional(),
    agent_totals: zAgentTotals,
    rate_limits: z.record(z.string(), z.unknown()).optional()
});

export const zCounter = z.object({
    count: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zGetHealthData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zGetSymphonySnapshotData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        workflow_id: z.string().optional()
    }).optional()
});

export const zStartSymphonyData = z.object({
    body: zStartSymphonyRequest.optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zStopSymphonyData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        workflow_id: z.string().optional()
    }).optional()
});

export const zGetSymphonyWorkflowsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zGetCounterData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zIncrementCounterData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});
