// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zHealthResponse = z.object({
  status: z.string(),
  symphony_running: z.boolean(),
  symphony_workflow_path: z.string().nullish(),
  symphony_last_error: z.string().nullish(),
});

export const zStartSymphonyRequest = z.object({
  workflow_path: z.string().optional(),
  http_port: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .nullish(),
});

export const zStartSymphonyResult = z.object({
  running: z.boolean(),
  workflow_path: z.string().nullish(),
});

export const zStopSymphonyResult = z.object({
  running: z.boolean(),
});

export const zSymphonyLiveSession = z.object({
  session_id: z.string().nullish(),
  thread_id: z.string().nullish(),
  turn_id: z.string().nullish(),
  codex_app_server_pid: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .nullish(),
  last_codex_event: z.string().nullish(),
  last_codex_timestamp: z.iso.datetime().nullish(),
  last_codex_message: z.string().nullish(),
  codex_input_tokens: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  codex_output_tokens: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  codex_total_tokens: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  turn_count: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

export const zSymphonyRetryEntry = z.object({
  issue_id: z.string(),
  identifier: z.string(),
  attempt: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  due_at: z.iso.datetime(),
  error: z.string().nullish(),
  delay_type: z.string().nullish(),
});

export const zSymphonyBlockerRef = z.object({
  id: z.string().nullish(),
  identifier: z.string().nullish(),
  state: z.string().nullish(),
});

export const zSymphonyIssue = z.object({
  id: z.string(),
  identifier: z.string(),
  title: z.string(),
  description: z.string().nullish(),
  priority: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .nullish(),
  state: z.string(),
  branch_name: z.string().nullish(),
  url: z.string().nullish(),
  labels: z.array(z.string()).optional(),
  blocked_by: z.array(zSymphonyBlockerRef).optional(),
  created_at: z.iso.datetime().nullish(),
  updated_at: z.iso.datetime().nullish(),
});

export const zSymphonyRunningEntry = z.object({
  issue: zSymphonyIssue,
  issue_id: z.string(),
  issue_identifier: z.string(),
  attempt: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .nullish(),
  workspace_path: z.string(),
  started_at: z.iso.datetime(),
  phase: z.string(),
  live: zSymphonyLiveSession,
});

export const zCodexTotals = z.object({
  input_tokens: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  output_tokens: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  total_tokens: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  seconds_running: z.number(),
});

export const zSymphonySnapshot = z.object({
  running: z.array(zSymphonyRunningEntry),
  retrying: z.array(zSymphonyRetryEntry),
  codex_totals: zCodexTotals,
  rate_limits: z.record(z.string(), z.unknown()).optional(),
});

export const zCounter = z.object({
  count: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

export const zGetHealthData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zGetSymphonySnapshotData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zStartSymphonyData = z.object({
  body: zStartSymphonyRequest.optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zStopSymphonyData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zGetCounterData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zIncrementCounterData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});
