BEGIN;

ALTER TABLE symphony_state
    ADD COLUMN IF NOT EXISTS workflow_id TEXT;

UPDATE symphony_state
SET workflow_id = 'default'
WHERE workflow_id IS NULL;

ALTER TABLE symphony_state
    ALTER COLUMN workflow_id SET NOT NULL;

DO $$
BEGIN
    ALTER TABLE symphony_state
        ADD CONSTRAINT symphony_state_workflow_id_key UNIQUE (workflow_id);
EXCEPTION
    WHEN duplicate_object THEN
        NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE symphony_state
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION
    WHEN duplicate_object THEN
        NULL;
END $$;

ALTER TABLE symphony_completed_attempts
    ADD COLUMN IF NOT EXISTS workflow_id TEXT;

UPDATE symphony_completed_attempts
SET workflow_id = 'default'
WHERE workflow_id IS NULL;

ALTER TABLE symphony_completed_attempts
    ALTER COLUMN workflow_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS symphony_completed_attempts_workflow_created_at_idx
    ON symphony_completed_attempts (workflow_id, created_at DESC);

COMMIT;

